# Generated by Django 5.1.5 on 2025-01-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
