# Generated by Django 5.1.5 on 2025-01-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_alter_timetable_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lecture_end',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture_start',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
