# Generated by Django 5.1.5 on 2025-01-23 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_alter_attendance_lecture_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_data', models.TextField()),
                ('subjects', models.ManyToManyField(to='student_management_app.subjects')),
            ],
        ),
    ]
