# Generated by Django 5.1.5 on 2025-01-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_weeklyreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyReport',
        ),
    ]
